"""Make exercise session_id non-nullable, block_id optional

Revision ID: 1c651b366cc7
Revises: 845c819d2f27
Create Date: 2026-01-03 20:08:01.439358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c651b366cc7'
down_revision: Union[str, Sequence[str], None] = '845c819d2f27'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('session_id', sa.Integer(), nullable=False))
    op.alter_column('exercises', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_exercises_session_id'), 'exercises', ['session_id'], unique=False)
    op.create_foreign_key(None, 'exercises', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_index(op.f('ix_exercises_session_id'), table_name='exercises')
    op.alter_column('exercises', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('exercises', 'session_id')
    # ### end Alembic commands ###
