"""Small changes Exercise table

Revision ID: 1e35d41303e7
Revises: 1c651b366cc7
Create Date: 2026-01-06 10:02:51.952636

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e35d41303e7'
down_revision: Union[str, Sequence[str], None] = '1c651b366cc7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('exercises', 'position',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_index(op.f('ix_exercise_position'), table_name='exercises')
    # op.create_index('ix_block_position', 'exercises', ['block_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_block_position', table_name='exercises')
    op.create_index(op.f('ix_exercise_position'), 'exercises', ['position'], unique=False)
    op.alter_column('exercises', 'position',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
