"""New small changes Exercise table

Revision ID: 416264c17545
Revises: 1e35d41303e7
Create Date: 2026-01-06 10:14:26.665511

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '416264c17545'
down_revision: Union[str, Sequence[str], None] = '1e35d41303e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_block_exercise_position'), 'exercises', type_='unique')
    op.create_index('ix_exercise_position', 'exercises', ['position'], unique=False)
    op.create_unique_constraint('uix_session_exercise_position', 'exercises', ['session_id', 'position'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uix_session_exercise_position', 'exercises', type_='unique')
    op.drop_index('ix_exercise_position', table_name='exercises')
    op.create_unique_constraint(op.f('uix_block_exercise_position'), 'exercises', ['block_id', 'position'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
