"""Add cascade deletes for user, session, block, exercise

Revision ID: 57123e26b043
Revises: b1142657aea9
Create Date: 2026-01-11 19:35:34.072695

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '57123e26b043'
down_revision: Union[str, Sequence[str], None] = 'b1142657aea9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('blocks_session_id_fkey'), 'blocks', type_='foreignkey')
    op.create_foreign_key(None, 'blocks', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('exercises_session_id_fkey'), 'exercises', type_='foreignkey')
    op.drop_constraint(op.f('exercises_block_id_fkey'), 'exercises', type_='foreignkey')
    op.create_foreign_key(None, 'exercises', 'blocks', ['block_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exercises', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('photos_session_id_fkey'), 'photos', type_='foreignkey')
    op.create_foreign_key(None, 'photos', 'sessions', ['session_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.create_foreign_key(op.f('photos_session_id_fkey'), 'photos', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.drop_constraint(None, 'exercises', type_='foreignkey')
    op.create_foreign_key(op.f('exercises_block_id_fkey'), 'exercises', 'blocks', ['block_id'], ['id'])
    op.create_foreign_key(op.f('exercises_session_id_fkey'), 'exercises', 'sessions', ['session_id'], ['id'])
    op.drop_constraint(None, 'blocks', type_='foreignkey')
    op.create_foreign_key(op.f('blocks_session_id_fkey'), 'blocks', 'sessions', ['session_id'], ['id'])
    # ### end Alembic commands ###
