"""Initial schema with UUID

Revision ID: 73db2a4f8ba6
Revises: 
Create Date: 2026-01-17 19:50:12.082441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '73db2a4f8ba6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('location_type', sa.Enum('crossfit', 'gym', 'none', name='locationtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('location_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('session_type', sa.Enum('wod', 'gym', 'weightlifting', 'fbb', 'compet', 'hyrox', 'open', 'team', name='sessiontype'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['location_id'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_location_id'), 'sessions', ['location_id'], unique=False)
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('blocks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('block_type', sa.Enum('amrap', 'emom', 'for_time', 'metcon', 'skill', name='blocktype'), nullable=False),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_id', 'position', name='uix_session_block_position')
    )
    op.create_index('ix_block_position', 'blocks', ['position'], unique=False)
    op.create_index(op.f('ix_blocks_session_id'), 'blocks', ['session_id'], unique=False)
    op.create_table('photos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=255), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_photos_session_id'), 'photos', ['session_id'], unique=False)
    op.create_table('exercises',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=True),
    sa.Column('block_id', sa.UUID(), nullable=True),
    sa.Column('exercise_type', sa.Enum('air_squat', 'back_squat', 'bear_complex', 'bear_walk', 'box_jump', 'broad_jump', 'burpee', 'burpee_pull_up', 'chest_to_bar', 'chin_up', 'clean', 'deadlift', 'devil_press', 'dip', 'double_under', 'front_squat', 'hand_release_push_up', 'handstand_push_up', 'hollow_rock', 'jumping_jacks', 'jumping_lunges', 'kettlebell_snatch', 'kettlebell_swing', 'knees_to_elbows', 'lunge', 'man_maker', 'medicine_ball_clean', 'mountain_climber', 'muscle_up', 'overhead_squat', 'overhead_walking_lunge', 'pistol_squat', 'plank', 'pull_up', 'push_jerk', 'push_press', 'push_up', 'shoulder_press', 'sit_up', 'snatch', 'squat', 'step_up', 'sumo_deadlift_high_pull', 'superman', 'thruster', 'toes_to_bar', 'tuck_jump', 'v_up', 'wall_ball', 'wall_walk', name='exercisetype'), nullable=False),
    sa.Column('weight_kg', sa.Float(), nullable=True),
    sa.Column('repetitions', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Float(), nullable=True),
    sa.Column('distance_meters', sa.Float(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True, comment='Position in session timeline (only for free exercises)'),
    sa.Column('position_in_block', sa.Integer(), nullable=True, comment='Position inside a block (only if block_id is not null)'),
    sa.ForeignKeyConstraint(['block_id'], ['blocks.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_exercise_block_position', 'exercises', ['block_id', 'position_in_block'], unique=False)
    op.create_index('ix_exercise_session_position', 'exercises', ['session_id', 'position'], unique=False)
    op.create_index(op.f('ix_exercises_block_id'), 'exercises', ['block_id'], unique=False)
    op.create_index(op.f('ix_exercises_session_id'), 'exercises', ['session_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_exercises_session_id'), table_name='exercises')
    op.drop_index(op.f('ix_exercises_block_id'), table_name='exercises')
    op.drop_index('ix_exercise_session_position', table_name='exercises')
    op.drop_index('ix_exercise_block_position', table_name='exercises')
    op.drop_table('exercises')
    op.drop_index(op.f('ix_photos_session_id'), table_name='photos')
    op.drop_table('photos')
    op.drop_index(op.f('ix_blocks_session_id'), table_name='blocks')
    op.drop_index('ix_block_position', table_name='blocks')
    op.drop_table('blocks')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_location_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
