"""Initial migration

Revision ID: 845c819d2f27
Revises: 9b588541425e
Create Date: 2026-01-03 15:56:22.294842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '845c819d2f27'
down_revision: Union[str, Sequence[str], None] = '9b588541425e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('location_type', sa.Enum('crossfit', 'gym', 'none', name='locationtype'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sessions', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_sessions_location_id'), 'sessions', ['location_id'], unique=False)
    op.create_foreign_key(None, 'sessions', 'locations', ['location_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sessions', type_='foreignkey')
    op.drop_index(op.f('ix_sessions_location_id'), table_name='sessions')
    op.drop_column('sessions', 'location_id')
    op.drop_table('locations')
    # ### end Alembic commands ###
