"""Recreate all models

Revision ID: 9b588541425e
Revises: 4574c66124b7
Create Date: 2025-12-27 12:41:32.683669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b588541425e'
down_revision: Union[str, Sequence[str], None] = '4574c66124b7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('blocks', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('exercises', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('photos', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('sessions', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('photos', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('exercises', 'block_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('blocks', 'session_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
