"""Refactor exercise positions with block support

Revision ID: b1142657aea9
Revises: f6198acb5e28
Create Date: 2026-01-06 14:32:58.459862

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1142657aea9'
down_revision: Union[str, Sequence[str], None] = 'f6198acb5e28'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('exercises', sa.Column('position_in_block', sa.Integer(), nullable=True, comment='Position inside a block (only if block_id is not null)'))
    op.alter_column('exercises', 'position',
               existing_type=sa.INTEGER(),
               nullable=True,
               comment='Position in session timeline (only for free exercises)')
    op.drop_index(op.f('ix_exercise_position'), table_name='exercises')
    op.create_index('ix_exercise_block_position', 'exercises', ['block_id', 'position_in_block'], unique=False)
    op.create_index('ix_exercise_session_position', 'exercises', ['session_id', 'position'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_exercise_session_position', table_name='exercises')
    op.drop_index('ix_exercise_block_position', table_name='exercises')
    op.create_index(op.f('ix_exercise_position'), 'exercises', ['position'], unique=False)
    op.alter_column('exercises', 'position',
               existing_type=sa.INTEGER(),
               nullable=False,
               comment=None,
               existing_comment='Position in session timeline (only for free exercises)')
    op.drop_column('exercises', 'position_in_block')
    # ### end Alembic commands ###
