"""New small changes again Exercise table

Revision ID: f6198acb5e28
Revises: 416264c17545
Create Date: 2026-01-06 12:08:18.481489

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f6198acb5e28'
down_revision: Union[str, Sequence[str], None] = '416264c17545'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('uix_session_exercise_position'), 'exercises', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uix_session_exercise_position'), 'exercises', ['session_id', 'position'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
